Importing the Dependencies
italicized text

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
# loading the dataset  to a Pandas DataFrame
credit_card_data = pd.read_csv("/content/creditcard.csv")

In [ ]:
# First 5  rows of dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [ ]:
# to print 5 last rows in dataset
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [ ]:
# dataset informations
#Null values means missing values
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [ ]:
#checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
df1= credit_card_data['Class']
df1.head(20)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: Class, dtype: int64

In [ ]:
# distribution of legit transactions & fraudulent transaction
credit_card_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [ ]:
credit_card_data['Time'].value_counts()

163152.0    36
64947.0     26
68780.0     25
3767.0      21
3770.0      20
            ..
127750.0     1
62260.0      1
62259.0      1
127753.0     1
172792.0     1
Name: Time, Length: 124592, dtype: int64

In [ ]:
credit_card_data['Time'].head()

0    0.0
1    0.0
2    1.0
3    1.0
4    2.0
Name: Time, dtype: float64

Dataset is highly unbalanced
0-> Normal Transaction
1-> Fradulent transaction

In [ ]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [ ]:
# statistical measure of data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [ ]:
# compare the values for both

In [ ]:
credit_card_data.groupby('Amount').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Class
Amount,,,,,,,,,,,,,,,,,,,,,
0.00,89370.688767,0.054099,0.312778,0.510623,1.858651,0.347416,0.202163,-0.389134,-0.004279,-0.227101,...,-0.152165,0.007598,0.249425,-0.022854,-0.031137,0.078709,0.211661,-0.039352,-0.029876,0.014795
0.01,82146.279944,-0.620691,0.457427,0.507827,0.067665,0.152530,0.086442,-0.264066,-0.106977,1.148250,...,0.035782,-0.180137,0.063045,0.030496,0.054680,0.138309,0.063259,0.100271,0.046239,0.006964
0.02,87315.576471,0.170367,-0.274388,0.966057,-1.299248,-0.586961,0.778127,-1.243272,0.148391,0.079912,...,0.036472,0.352341,0.888831,-0.094633,0.102567,0.133680,-0.128601,0.063126,0.011449,0.000000
0.03,99923.333333,-0.327433,-0.505556,0.237874,-1.734726,0.395806,-0.564964,-0.617002,-0.663259,0.157840,...,0.189620,-0.407880,-0.040707,-0.118674,-0.495686,0.651412,-0.291969,-0.027039,-0.091406,0.000000
0.04,91373.000000,-0.336613,-0.782633,0.676427,0.351779,1.030341,-0.487902,-0.847386,0.312604,0.495719,...,0.185313,0.180197,0.404117,0.120962,0.037834,0.005724,-0.201646,-0.005548,0.031668,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11898.09,46253.000000,-21.780665,-38.305310,-12.122469,9.752791,-12.880794,4.256017,14.785051,-2.818253,-0.667338,...,24.133894,7.437478,-5.619439,-10.547038,0.653249,-4.232409,-0.480459,-2.257913,2.082488,0.000000
12910.93,42951.000000,-23.712839,-42.172688,-13.320825,9.925019,-13.945538,5.564891,15.710644,-2.844253,-1.580725,...,26.237391,7.921600,-6.320710,-11.310338,0.404175,-4.547278,-1.577118,-2.357385,2.253662,0.000000
18910.00,95286.000000,-34.549296,-60.464618,-21.340854,16.875344,-19.229075,6.335259,24.422716,-4.964566,0.188912,...,38.117209,11.502580,-9.499423,-16.513186,0.744341,-7.081325,-2.604551,-3.550963,3.250802,0.000000
19656.53,48401.000000,-36.802320,-63.344698,-20.645794,16.715537,-20.672064,7.694002,24.956587,-4.730111,-2.687312,...,39.420904,11.455313,-10.933144,-17.173665,1.180700,-7.025783,-2.534330,-3.602479,3.450224,0.000000
25691.16,166198.000000,-35.548539,-31.850484,-48.325589,15.304184,-113.743307,73.301626,120.589494,-27.347360,-3.872425,...,-54.497720,-21.620120,5.712303,-1.581098,4.584549,4.554683,3.415636,31.612198,-15.430084,0.000000

In [ ]:
credit_card_data.groupby('Amount').mean().head(100)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Class
Amount,,,,,,,,,,,,,,,,,,,,,
0.00,89370.688767,0.054099,0.312778,0.510623,1.858651,0.347416,0.202163,-0.389134,-0.004279,-0.227101,...,-0.152165,0.007598,0.249425,-0.022854,-0.031137,0.078709,0.211661,-0.039352,-0.029876,0.014795
0.01,82146.279944,-0.620691,0.457427,0.507827,0.067665,0.152530,0.086442,-0.264066,-0.106977,1.148250,...,0.035782,-0.180137,0.063045,0.030496,0.054680,0.138309,0.063259,0.100271,0.046239,0.006964
0.02,87315.576471,0.170367,-0.274388,0.966057,-1.299248,-0.586961,0.778127,-1.243272,0.148391,0.079912,...,0.036472,0.352341,0.888831,-0.094633,0.102567,0.133680,-0.128601,0.063126,0.011449,0.000000
0.03,99923.333333,-0.327433,-0.505556,0.237874,-1.734726,0.395806,-0.564964,-0.617002,-0.663259,0.157840,...,0.189620,-0.407880,-0.040707,-0.118674,-0.495686,0.651412,-0.291969,-0.027039,-0.091406,0.000000
0.04,91373.000000,-0.336613,-0.782633,0.676427,0.351779,1.030341,-0.487902,-0.847386,0.312604,0.495719,...,0.185313,0.180197,0.404117,0.120962,0.037834,0.005724,-0.201646,-0.005548,0.031668,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.96,80731.000000,-0.892505,1.242110,0.297683,-0.255608,0.929881,0.483606,0.328906,-0.177875,-0.011091,...,0.191723,-0.132669,0.153441,-0.089190,0.251712,0.073492,-0.040763,-0.203104,0.073631,0.000000
0.97,98910.555556,0.081356,0.466849,0.101161,0.077721,0.482118,-0.555513,0.002994,-0.306143,0.233869,...,-0.174639,0.279972,-0.198232,-0.064360,-0.008119,0.098561,0.176601,0.012579,0.020819,0.000000
0.98,106270.900000,-1.848213,2.110270,-1.178350,-0.398428,-0.221404,-0.672092,-0.214012,0.890252,0.397100,...,0.238009,0.207378,0.537302,0.066237,0.072676,-0.076827,-0.118888,0.251439,0.159511,0.000000
0.99,103900.088542,0.489256,0.575873,-0.262251,0.069929,0.405400,-0.477538,0.239146,-0.018537,0.077235,...,-0.047678,-0.182600,-0.510481,0.110392,0.003175,-0.144238,0.089696,0.028774,0.016337,0.000000
1.00,94222.672195,0.243654,0.441987,-0.296872,0.074735,0.330330,-0.217924,-0.166445,-0.091646,0.302943,...,-0.093177,0.033458,0.298029,-0.091262,-0.030230,0.216657,-0.225993,0.029114,-0.005987,0.008255

In [ ]:
print(fraud.head())

        Time        V1        V2        V3        V4        V5        V6  \
541    406.0 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623    472.0 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823
4920  4462.0 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788
6108  6986.0 -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536
6329  7519.0  1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746

            V7        V8        V9  ...       V21       V22       V23  \
541  -2.537387  1.391657 -2.770089  ...  0.517232 -0.035049 -0.465211
623   0.325574 -0.067794 -0.270953  ...  0.661696  0.435477  1.375966
4920  0.562320 -0.399147 -0.238253  ... -0.294166 -0.932391  0.172726
6108 -3.496197 -0.248778 -0.247768  ...  0.573574  0.176968 -0.436207
6329  1.713445 -0.496358 -1.282858  ... -0.379068 -0.704181 -0.656805

           V24       V25       V26       V27       V28  Amount  Class
541   0.320198  0.044519  0.177840  0.261145 -0.143276    0.00      1
623  -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00      1
4920 -0.087330 -0.156114 -0.542628  0.039566 -0.153029  239.93      1
6108 -0.053502  0.252405 -0.657488 -0.827136  0.849573   59.00      1
6329 -1.632653  1.488901  0.566797 -0.010016  0.146793    1.00      1

[5 rows x 31 columns]

In [ ]:
#Under-Sampling
#Build a sample dataset containing similar distribution of normal transaction and Fradulent
#Number of Fradulent transaction--> 492

In [ ]:
legit_sample = legit.sample(n=492)

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head(20)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
281114,169949.0,-0.242857,1.110519,-0.491036,-0.330854,0.151497,-1.258273,0.617639,0.213616,-0.006091,...,0.404137,1.257120,-0.060769,-0.006060,-0.822071,-0.210718,0.381154,0.255046,1.99,0
167275,118589.0,1.508131,-3.183453,-1.427208,-2.231440,-0.163728,4.367590,-2.272823,1.098659,-0.534074,...,0.269032,0.451791,-0.008639,0.717949,-0.607256,-0.097712,0.037256,0.029915,371.45,0
247627,153639.0,-0.743521,-0.614607,1.930470,-3.357922,-0.610923,-0.614542,-0.161201,0.049658,2.446518,...,0.346530,1.277139,-0.293938,0.010439,-0.354535,-0.945582,-0.018970,-0.067828,42.48,0
83307,59783.0,1.211857,0.214647,0.251622,0.655917,-0.296912,-0.632716,-0.075810,0.005932,0.218520,...,-0.274280,-0.818288,0.173728,-0.000382,0.100809,0.128299,-0.014819,0.024753,1.98,0
167109,118490.0,-0.943601,1.408577,-0.501470,-0.634583,-0.296040,-0.996443,0.155906,0.824273,-0.382017,...,-0.151873,-0.530307,0.186825,0.053106,-0.450391,0.125376,0.099243,0.013010,8.99,0
25303,33549.0,1.160552,0.138309,0.499842,0.459257,-0.229506,-0.190972,-0.099860,0.070432,-0.240208,...,-0.172273,-0.510273,0.145303,0.016856,0.116844,0.105716,-0.016842,0.006964,8.99,0
133343,80344.0,0.926268,-0.860259,0.858521,0.104440,-0.945268,0.628123,-0.716966,0.355751,1.016478,...,-0.111526,-0.342292,-0.039078,-0.227305,0.020472,0.963945,-0.046023,0.016575,123.40,0
272869,165304.0,-0.698898,0.812196,1.475654,-0.701722,-0.104815,-0.154156,0.270052,0.156309,0.546373,...,0.192245,0.880084,-0.130792,1.153019,-0.303826,0.502448,0.479709,0.297551,9.20,0
155379,105273.0,1.787031,-0.634216,-0.669182,0.375334,-0.201481,0.356438,-0.629464,0.054184,2.291408,...,0.142614,0.515122,0.012663,0.152434,-0.144110,-0.315277,-0.022881,-0.031733,118.37,0
162596,115236.0,2.143272,-1.250471,-0.115626,-1.178457,-1.043065,0.844719,-1.798964,0.344420,0.356257,...,0.419303,1.270277,0.104834,-0.101680,-0.297751,-0.092252,0.049595,-0.042152,9.99,0
233752,147690.0,2.018054,0.068235,-1.616587,0.351728,0.327757,-0.677923,0.045800,-0.067114,0.313160,...,-0.307438,-0.847410,0.357600,0.653225,-0.333795,0.144583,-0.070270,-0.039993,1.98,0
162951,115515.0,1.829126,-0.730894,-0.394126,-0.020959,0.088813,2.019948,-1.281865,0.795263,1.447702,...,0.135680,0.579551,0.346011,-0.858560,-0.600597,-0.353321,0.093623,-0.048274,6.01,0
86036,61056.0,-0.819088,0.713359,0.918815,0.611819,1.461948,-0.109799,0.592448,-0.055753,-0.991724,...,0.039137,0.287454,-0.227335,-0.351370,-0.163732,0.489979,-0.210057,-0.038157,0.76,0
89392,62559.0,-1.045308,1.229996,1.836088,-0.490770,0.377247,-0.181271,1.236100,-0.577815,0.822721,...,-0.477429,-0.391468,-0.088699,0.165034,-0.257612,-0.021046,0.045192,-0.537788,9.42,0
181291,124907.0,1.507448,-0.790149,-2.136197,0.221041,0.741850,0.882397,0.030622,0.274540,0.800532,...,-0.035597,-0.224449,0.005040,-1.740473,-0.303041,0.002519,-0.000331,-0.013917,210.33,0
42420,41098.0,-1.463636,0.752803,2.193647,3.497622,-0.625935,0.775829,-0.164602,0.539852,-0.453914,...,-0.392469,-0.506575,0.463762,0.429576,-0.076048,0.039546,-0.037307,-0.043659,53.85,0
180410,124531.0,-0.489167,-0.478932,-0.903357,-0.440938,2.422457,1.011198,0.271806,0.276541,0.477791,...,-0.145517,-0.028760,0.406436,-1.090138,-0.495846,-0.049294,-0.215457,-0.153404,40.78,0
80544,58534.0,-1.339343,0.842304,2.210153,3.009876,-0.501056,1.506612,0.044767,0.574622,-0.545759,...,-0.188658,-0.159114,-0.241138,-0.402550,0.057283,0.231537,0.067849,-0.249524,120.00,0
171400,120622.0,-0.051381,0.941162,-0.569887,-0.208470,0.403897,-1.198001,1.341323,-0.410398,0.580721,...,0.161420,0.904102,-0.140614,-0.126493,-0.357388,-0.152739,0.347678,0.017932,72.52,0
160236,113177.0,2.024321,-0.226440,-1.448441,0.092395,0.086997,-0.591456,-0.083336,-0.014376,0.782123,...,0.303162,0.896505,0.037945,0.675086,0.234090,-0.463341,-0.009713,-0.061275,1.00,0

In [ ]:
new_dataset.tail(20)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
261473,160034.0,-2.349340,1.512604,-2.647497,1.753792,0.406328,-2.188494,-0.686935,-0.547984,-0.099528,...,-0.088519,-0.595178,0.258148,0.061901,-0.354180,-1.152671,-0.736073,0.733703,4.90,1
261925,160243.0,-2.783865,1.596824,-2.084844,2.512986,-1.446749,-0.828496,-0.732262,-0.203329,-0.347046,...,0.203563,0.293268,0.199568,0.146868,0.163602,-0.624085,-1.333100,0.428634,156.00,1
262560,160537.0,0.567539,3.309385,-6.631268,6.394574,-0.054172,-2.396535,-2.792489,0.514811,-3.541780,...,0.614221,-0.365047,-0.180409,-0.523271,0.645054,0.246466,0.902675,0.473571,4.69,1
262826,160665.0,-0.417340,4.700055,-7.521767,7.671884,0.260821,-2.646693,-2.854432,0.958783,-4.588536,...,0.622200,-0.437708,-0.090358,-0.742802,-0.312361,0.502575,0.821390,0.372379,0.77,1
263080,160791.0,2.132386,0.705608,-3.530759,0.514779,1.527175,-1.716268,1.132791,-0.574214,0.128904,...,0.163739,0.703910,-0.245076,0.460049,0.920281,-0.216586,-0.026219,-0.025001,1.00,1
263274,160870.0,-0.644278,5.002352,-8.252739,7.756915,-0.216267,-2.751496,-3.358857,1.406268,-4.403852,...,0.587728,-0.605759,0.033746,-0.756170,-0.008172,0.532772,0.663970,0.192067,0.77,1
263324,160895.0,-0.848290,2.719882,-6.199070,3.044437,-3.301910,-1.992117,-3.734902,1.520079,-2.548788,...,1.125229,0.805258,0.199119,0.035206,0.012159,0.601658,0.137468,-0.171397,127.14,1
263877,161154.0,-3.387601,3.977881,-6.978585,1.657766,-1.100500,-3.599487,-3.686651,1.942252,-3.065089,...,1.043587,0.262189,-0.479224,-0.326638,-0.156939,0.113807,0.354124,0.287592,0.38,1
268375,163181.0,-5.238808,0.623013,-5.784507,1.678889,-0.364432,-0.477295,-4.276132,-0.695173,-2.971644,...,-0.326140,1.509239,-0.215966,-0.245727,0.893041,0.865758,0.854657,-0.964482,39.98,1
272521,165132.0,-7.503926,-0.360628,-3.830952,2.486103,2.497367,1.332437,-6.783964,-15.415385,0.465512,...,-6.389132,2.249964,1.670508,0.140450,0.162147,1.207731,1.268958,0.097538,12.31,1
274382,165981.0,-5.766879,-8.402154,0.056543,6.950983,9.880564,-5.773192,-5.748879,0.721743,-1.076274,...,0.880395,-0.130436,2.241471,0.665346,-1.890041,-0.120803,0.073269,0.583799,0.00,1
274475,166028.0,-0.956390,2.361594,-3.171195,1.970759,0.474761,-1.902598,-0.055178,0.277831,-1.745854,...,0.473211,0.719400,0.122458,-0.255650,-0.619259,-0.484280,0.683535,0.443299,39.90,1
275992,166831.0,-2.027135,-1.131890,-1.135194,1.086963,-0.010547,0.423797,3.790880,-1.155595,-0.063434,...,-0.315105,0.575520,0.490842,0.756502,-0.142685,-0.602777,0.508712,-0.091646,634.30,1
276071,166883.0,2.091900,-0.757459,-1.192258,-0.755458,-0.620324,-0.322077,-1.082511,0.117200,-0.140927,...,0.288253,0.831939,0.142007,0.592615,-0.196143,-0.136676,0.020182,-0.015470,19.95,1
276864,167338.0,-1.374424,2.793185,-4.346572,2.400731,-1.688433,0.111136,-0.922038,-2.149930,-2.027474,...,-0.870779,0.504849,0.137994,0.368275,0.103137,-0.414209,0.454982,0.096711,349.08,1
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [ ]:
p = new_dataset[new_dataset.Class == 1].shape
p

(492, 31)

In [ ]:
p1 = new_dataset[new_dataset.Class == 0].shape
p1

(492, 31)

In [ ]:
new_dataset['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,96048.447154,-0.118078,-0.002536,-0.031870,-0.045366,0.109343,0.038530,-0.044954,0.042705,-0.007311,...,0.036731,-0.013643,0.034591,0.004274,-0.015137,0.026341,0.002757,-0.028187,-0.022232,80.997907
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting the data into features & Targets

In [ ]:
X = new_dataset.drop(columns='Class', axis=1) # almost full dataset except class
Y = new_dataset['Class'] #class containing dataset

In [ ]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
281114,169949.0,-0.242857,1.110519,-0.491036,-0.330854,0.151497,-1.258273,0.617639,0.213616,-0.006091,...,-0.214536,0.404137,1.257120,-0.060769,-0.006060,-0.822071,-0.210718,0.381154,0.255046,1.99
167275,118589.0,1.508131,-3.183453,-1.427208,-2.231440,-0.163728,4.367590,-2.272823,1.098659,-0.534074,...,0.394132,0.269032,0.451791,-0.008639,0.717949,-0.607256,-0.097712,0.037256,0.029915,371.45
247627,153639.0,-0.743521,-0.614607,1.930470,-3.357922,-0.610923,-0.614542,-0.161201,0.049658,2.446518,...,-0.238765,0.346530,1.277139,-0.293938,0.010439,-0.354535,-0.945582,-0.018970,-0.067828,42.48
83307,59783.0,1.211857,0.214647,0.251622,0.655917,-0.296912,-0.632716,-0.075810,0.005932,0.218520,...,-0.192409,-0.274280,-0.818288,0.173728,-0.000382,0.100809,0.128299,-0.014819,0.024753,1.98
167109,118490.0,-0.943601,1.408577,-0.501470,-0.634583,-0.296040,-0.996443,0.155906,0.824273,-0.382017,...,-0.143675,-0.151873,-0.530307,0.186825,0.053106,-0.450391,0.125376,0.099243,0.013010,8.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [ ]:
Y

281114    0
167275    0
247627    0
83307     0
167109    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

Model Training

#Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(X_train, Y_train)

LogisticRegression()

For example, if variable y is a binary categorical variable with values 0 and 1 and there are 25% of zeros and 75% of ones, stratify=y will make sure that your random split has 25% of 0's and 75% of 1's.

In [ ]:
#Model Evaluation based on accuracy score

Model Evaluation

Accuracy Score:

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on training data : ', training_data_accuracy)

Accuracy on training data :  0.9174078780177891

In [ ]:
#Accuracy score  on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print("Accuracy score of test data :", test_data_accuracy)

Accuracy score of test data : 0.8984771573604061